version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: billing_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-billing_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-billing_password}
      POSTGRES_DB: ${POSTGRES_DB:-billing_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: billing_redis
    restart: always
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: billing_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://billing_user:billing_password@db:5432/billing_db}
      API_KEY_SECRET: ${API_KEY_SECRET:-ccf26ad1-c694-463a-834a-7e666d94424b}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL:-redis://redis:6379/0}
    depends_on:
      - db
      - redis

  worker:
    build: .
    container_name: billing_worker
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://billing_user:billing_password@db:5432/billing_db}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL:-redis://redis:6379/0}
    command: celery -A app.infrastructure.celery_config.celery_app worker --loglevel=info
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
